; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:firebeetle32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_size = 4MB
board_build.partitions = default.csv
extra_scripts = pre:patch_lidar.py
build_flags = 
	-D FLESPI_TOKEN=\"QZBImJsYXGlviI2NJprnuLAZs5Mzdl1p6y6NcXGJcA05wgbFShRxgwke65khn3Qy\"
	-D DEVICE_ID=\"8235942\"
	-D WIFI_SSID=\"Hotspot\"
	-D WIFI_PASSWORD=\"apricola\"
	-D OTA_PASSWORD=\"password\"
	-D OTA_HOSTNAME=\"lidar-scanner\"
lib_deps = 
	garmin/LIDAR-Lite@^3.0.6
	madhephaestus/ESP32Servo@^3.2.0
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	bblanchon/ArduinoJson@^7.2.2

[env:firebeetle32-ota]
platform = espressif32
board = esp32dev
framework = arduino
upload_protocol = espota
upload_port = lidar-scanner.local
upload_flags = 
	--auth=password
build_flags = 
	-D FLESPI_TOKEN=\"QZBImJsYXGlviI2NJprnuLAZs5Mzdl1p6y6NcXGJcA05wgbFShRxgwke65khn3Qy\"
	-D DEVICE_ID=\"8235942\"
	-D WIFI_SSID=\"WiFi2773ehy\"
	-D WIFI_PASSWORD=\"x2UuD59XJ\"
	-D OTA_PASSWORD=\"password\"
	-D OTA_HOSTNAME=\"lidar-scanner\"
lib_deps = 
	garmin/LIDAR-Lite@^3.0.6
	madhephaestus/ESP32Servo@^3.2.0
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	bblanchon/ArduinoJson@^7.2.2
